import '../providers/language_provider.dart';

class AppStrings {
  static final Map<AppLanguage, Map<String, String>> _localizedValues = {
    AppLanguage.portuguese: {
      'appTitle': 'Portfólio de Adriano Pontes',
      'name': 'Adriano Pontes',
      'jobTitle': 'Mobile Developer | MSc Software Engineering Student',
      'location': 'João Pessoa / Paraíba - Brasil',
      'aboutMe': 'Sobre Mim',
      'aboutMeContent': 'Desenvolvedor Full Stack com experiência em desenvolvimento de sistemas governamentais, aplicações para o mercado de crédito e terminais de autoatendimento. Atualmente trabalho no Núcleo de Excelência em Tecnologias Sociais (NEES), desenvolvendo sistemas que dão suporte ao Programa Nacional do Livro Didático (PNLD). Possuo sólidos conhecimentos em Flutter, Spring, Kotlin, VueJS, Firebase e PostgreSQL, além de experiência com metodologias ágeis como Scrum e ferramentas como Jira.',
      'skills': 'Habilidades',
      'experience': 'Experiência',
      'education': 'Educação',
      'publications': 'Publicações',
      'languages': 'Idiomas',
      'contact': 'Contato',
      'footer': 'Desenvolvido com Flutter, Provider e Material 3',
      'selectLanguage': 'Selecionar Idioma',
      'back': 'Voltar',
      'portuguese': 'Português',
      'english': 'Inglês',
      'spanish': 'Espanhol',
      'german': 'Alemão',
      'native': 'Nativo',
      'advanced': 'Avançado',
      'basic': 'Básico',
      'lightMode': 'Modo claro',
      'darkMode': 'Modo escuro',
      'backToTop': 'Voltar ao topo',
    },
    AppLanguage.english: {
      'appTitle': 'Adriano Pontes Portfolio',
      'name': 'Adriano Pontes',
      'jobTitle': 'Mobile Developer | MSc Software Engineering Student',
      'location': 'João Pessoa / Paraíba - Brazil',
      'aboutMe': 'About Me',
      'aboutMeContent': 'Full Stack Developer with experience in government systems, credit market applications, and self-service terminals. Currently working at the Center of Excellence in Social Technologies (NEES), developing systems that support the National Textbook Program (PNLD), one of the largest public book distribution initiatives in the world. I have solid knowledge in Flutter, Spring, Kotlin, VueJS, Firebase, and PostgreSQL, as well as experience with agile methodologies such as Scrum and tools like Jira.',
      'skills': 'Skills',
      'experience': 'Experience',
      'education': 'Education',
      'publications': 'Publications',
      'languages': 'Languages',
      'contact': 'Contact',
      'footer': 'Developed with Flutter, Provider and Material 3',
      'selectLanguage': 'Select Language',
      'back': 'Back',
      'portuguese': 'Portuguese',
      'english': 'English',
      'spanish': 'Spanish',
      'german': 'German',
      'native': 'Native',
      'advanced': 'Advanced',
      'basic': 'Basic',
      'lightMode': 'Light Mode',
      'darkMode': 'Dark Mode',
      'backToTop': 'Back to top',
    },
    AppLanguage.spanish: {
      'appTitle': 'Portafolio de Adriano Pontes',
      'name': 'Adriano Pontes',
      'jobTitle': 'Mobile Developer | MSc Software Engineering Student',
      'location': 'João Pessoa / Paraíba - Brasil',
      'aboutMe': 'Sobre Mí',
      'aboutMeContent': 'Desarrollador Full Stack con experiencia en sistemas gubernamentales, aplicaciones para el mercado crediticio y terminales de autoservicio. Actualmente trabajo en el Núcleo de Excelencia en Tecnologías Sociales (NEES), desarrollando sistemas que apoyan el Programa Nacional del Libro Didáctico (PNLD), una de las mayores iniciativas de distribución pública de libros del mundo. Tengo sólidos conocimientos en Flutter, Spring, Kotlin, VueJS, Firebase y PostgreSQL, además de experiencia con metodologías ágiles como Scrum y herramientas como Jira.',
      'skills': 'Habilidades',
      'experience': 'Experiencia',
      'education': 'Educación',
      'publications': 'Publicaciones',
      'languages': 'Idiomas',
      'contact': 'Contacto',
      'footer': 'Desarrollado con Flutter, Provider y Material 3',
      'selectLanguage': 'Seleccionar Idioma',
      'back': 'Volver',
      'portuguese': 'Portugués',
      'english': 'Inglés',
      'spanish': 'Español',
      'german': 'Alemán',
      'native': 'Nativo',
      'advanced': 'Avanzado',
      'basic': 'Básico',
      'lightMode': 'Modo claro',
      'darkMode': 'Modo oscuro',
      'backToTop': 'Volver arriba',
    },
    AppLanguage.german: {
      'appTitle': 'Portfolio von Adriano Pontes',
      'name': 'Adriano Pontes',
      'jobTitle': 'Mobile-Entwickler | MSc Software Engineering Student',
      'location': 'João Pessoa / Paraíba - Brasilien',
      'aboutMe': 'Über Mich',
      'aboutMeContent': 'Full-Stack-Entwickler mit Erfahrung in Regierungssystemen, Anwendungen für den Kreditmarkt und Selbstbedienungsterminals. Derzeit arbeite ich am Zentrum für Exzellenz in Sozialtechnologien (NEES) und entwickle Systeme, die das Nationale Lehrbuchprogramm (PNLD) unterstützen, eine der größten öffentlichen Buchverteilungsinitiativen der Welt. Ich verfüge über fundierte Kenntnisse in Flutter, Spring, Kotlin, VueJS, Firebase und PostgreSQL sowie Erfahrung mit agilen Methoden wie Scrum und Tools wie Jira.',
      'skills': 'Fähigkeiten',
      'experience': 'Erfahrung',
      'education': 'Bildung',
      'publications': 'Publikationen',
      'languages': 'Sprachen',
      'contact': 'Kontakt',
      'footer': 'Entwickelt mit Flutter, Provider und Material 3',
      'selectLanguage': 'Sprache Auswählen',
      'back': 'Zurück',
      'portuguese': 'Portugiesisch',
      'english': 'Englisch',
      'spanish': 'Spanisch',
      'german': 'Deutsch',
      'native': 'Muttersprache',
      'advanced': 'Fortgeschritten',
      'basic': 'Grundkenntnisse',
      'lightMode': 'Heller Modus',
      'darkMode': 'Dunkler Modus',
      'backToTop': 'Zurück nach oben',
    },
  };

  static String get(String key, AppLanguage language) {
    return _localizedValues[language]?[key] ?? key;
  }
}